######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 26 20:20:08 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /ad/eng/users/k/l/klausd/Desktop/535_Project/qt/projectQT/. .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
