######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 26 15:35:19 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /ad/eng/users/a/w/awelles/Desktop/ec535project_master/qt_stuff/. \
               .

# Input
HEADERS += window.h
SOURCES += main.cpp window.cpp
